Feature/feature a
Georjane/Enumerable-Methods pull request #1
Opened 2020-06-23 10:42 UTC by ldelbel

In this project, the goal was to build methods using the Enumerable Module. The following methods were built:

- my_each
- my_each_with_index
- my_select
- my_all?
- my_any?
- my_none?
- my_count
- my_map (and proc)
- my_inject

2020-06-23 11:59 UTC, stratospherique requested changes
### Great start @team :clap: :clap: However, some changes need to be applied in order to get approval for this project. Check :arrow_down: 

- **[REQUIRED]** No debugging instructions in committed code (as discussed [here](https://questions.microverse.org/t/debugging-instructions-code/346)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/section/debugging_requirement.png) from Pathwright)

- **[REQUIRED]** Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### :arrow_right:  my_each, my_each_with_index, my_select

* [x] consider the case when self is a range, a hash

### :arrow_right:  my_map, my_inject

* [x] consider the case when self is a range

##### :arrow_right:  gen

The issues with **my_none?**, **my_any?** and **my_all?** are similar. the methods should be able to: 

* [x] Handle the cases where no block is given (Hint: block_given?)
* [x] Return a suitable boolean result if no arguments were passed.
  ```ruby
	array = [false, true, false, nil, []]
	puts array.my_any? # should print true
	puts array.my_all? # should print false
	puts array.my_none? # should print false
  ```
* [x] Accept primitives, classes (i.e Integer, String, etc...) and Regex Expressions as arguments.
  ```ruby
	words = %w[dog door rod blade]
	puts words.my_all?(/c/) == words.all?(/c/) # false
	puts words.my_any?(/c/) == words.all?(/c/) # false
	puts words.my_none?(/c/) == words.all?(/c/) # true
  ```



### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-06-23 17:53 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,
Thank you for applying the suggested changes.
You did a great job !!

However, there are still some errors to fix.
Kindly read about them below, then fix them and submit a new code review request

Thanks
Mael FOSSO

2020-06-23 17:53 UTC, maelfosso commented on enumerable.rb
> +  end
```rb
2.6.5 :018 > words = %w[dog door rod blade]
 => ["dog", "door", "rod", "blade"] 
2.6.5 :019 > words.any?('cat')
 => false 
2.6.5 :020 > words.my_any?('cat')
 => false 
2.6.5 :021 > ws = words.dup
 => ["dog", "door", "rod", "blade"] 
2.6.5 :022 > ws[0] = 'cat'
 => "cat" 
2.6.5 :023 > ws.any?('cat')
 => true 
2.6.5 :024 > ws.my_any?('cat')
 => false 
2.6.5 :025 > 
```

2020-06-23 17:53 UTC, maelfosso commented on enumerable.rb
> +  end
```rb
2.6.5 :027 > words
 => ["dog", "door", "rod", "blade"] 
2.6.5 :028 > words.none?(5)
 => true 
2.6.5 :029 > words.my_none?(5)
 => true 
2.6.5 :030 > ws = words.dup
 => ["dog", "door", "rod", "blade"] 
2.6.5 :031 > ws[0] = 5
 => 5 
2.6.5 :032 > ws.none?(5)
 => false 
2.6.5 :033 > ws.my_none?(5)
 => true 
2.6.5 :034 > 
```

2020-06-23 17:53 UTC, maelfosso commented on enumerable.rb
> +  end
```rb
2.6.5 :013 > array
 => [4, 3, 3, 1, 1, 6, 5, 6, 6, 0, 7, 3, 1, 3, 5, 6, 3, 5, 2, 8, 6, 5, 6, 3, 6, 8, 1, 1, 7, 1, 0, 6, 2, 7, 3, 7, 5, 7, 6, 7, 6, 1, 8, 5, 7, 7, 0, 8, 6, 4, 2, 0, 0, 0, 8, 8, 0, 4, 0, 4, 2, 6, 2, 7, 2, 6, 0, 3, 8, 8, 5, 7, 7, 6, 5, 5, 5, 4, 5, 2, 4, 4, 2, 6, 4, 5, 3, 8, 1, 5, 3, 3, 2, 1, 5, 3, 1, 5, 3, 8] 
2.6.5 :014 > array.all?(3)
 => false 
2.6.5 :015 > array.my_all?(3)
 => true 
2.6.5 :016 > 
```

2020-06-23 17:53 UTC, maelfosso commented on enumerable.rb
> +  end
```rb
2.6.5 :037 > array
 => [4, 3, 3, 1, 1, 6, 5, 6, 6, 0, 7, 3, 1, 3, 5, 6, 3, 5, 2, 8, 6, 5, 6, 3, 6, 8, 1, 1, 7, 1, 0, 6, 2, 7, 3, 7, 5, 7, 6, 7, 6, 1, 8, 5, 7, 7, 0, 8, 6, 4, 2, 0, 0, 0, 8, 8, 0, 4, 0, 4, 2, 6, 2, 7, 2, 6, 0, 3, 8, 8, 5, 7, 7, 6, 5, 5, 5, 4, 5, 2, 4, 4, 2, 6, 4, 5, 3, 8, 1, 5, 3, 3, 2, 1, 5, 3, 1, 5, 3, 8] 
2.6.5 :038 > array.count(3)
 => 13 
2.6.5 :039 > array.my_count(3)
Traceback (most recent call last):
        5: from /usr/share/rvm/rubies/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /usr/share/rvm/rubies/ruby-2.6.5/bin/irb:23:in `load'
        3: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        2: from (irb):39
        1: from enumerable.rb:79:in `my_count'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :040 > 
```

2020-06-23 17:53 UTC, maelfosso commented on enumerable.rb
> +  end
```rb
2.6.5 :052 > my_proc = proc {|num| num > 10 }
 => #<Proc:0x00000000029401b8@(irb):52> 
2.6.5 :053 > array.my_map(my_proc) {|num| num < 10 } == array.map(&my_proc)
 => false 
2.6.5 :054 > array
 => [4, 3, 3, 1, 1, 6, 5, 6, 6, 0, 7, 3, 1, 3, 5, 6, 3, 5, 2, 8, 6, 5, 6, 3, 6, 8, 1, 1, 7, 1, 0, 6, 2, 7, 3, 7, 5, 7, 6, 7, 6, 1, 8, 5, 7, 7, 0, 8, 6, 4, 2, 0, 0, 0, 8, 8, 0, 4, 0, 4, 2, 6, 2, 7, 2, 6, 0, 3, 8, 8, 5, 7, 7, 6, 5, 5, 5, 4, 5, 2, 4, 4, 2, 6, 4, 5, 3, 8, 1, 5, 3, 3, 2, 1, 5, 3, 1, 5, 3, 8] 
2.6.5 :055 > 
```

2020-06-23 22:45 UTC, ldelbel commented
Fixed the problems pointed for my_all?, my_any? and my_none?

But for my_map, kindly check again the test that was made. This is what was given:

2.6.5 :052 > my_proc = proc {|num| num > 10 }
 => #<Proc:0x00000000029401b8@(irb):52> 
2.6.5 :053 > array.my_map(my_proc) {|num| num < 10 } == array.map(&my_proc)
 => false 

Note that in my_proc the test is 'num > 10' (greater than) and in the block given for array.my_map was 'num < 10' (less than). When I did the same test with only .map it returned 'false' as well. Please check again.

2020-06-23 23:21 UTC, MarioDena requested changes
Hello Great work implementing your classes however there are still some changes to do.

## Changes required 

Please check my comments.

2020-06-23 23:21 UTC, MarioDena commented on enumerable.rb
> +  end
- [ ] My each should, when a block is given and self is a range returns the range itself after calling the given block once for each element in self. You are returning an array in this scenario we need to return a range.

- [ ] Same bad return for when using hashes. When a block is given when self is a hash behaves like #each calls the given block once for each element in self. You need to return a hash you are giving a string back.

2020-06-23 23:21 UTC, MarioDena commented on enumerable.rb
> +  end
Same problems from my_each apply here.

2020-06-23 23:21 UTC, MarioDena commented on enumerable.rb
> +  end
- [ ] when no block or argument is given returns true when none of the collection members are false or nil. I got a true when a false was expected.

- [ ] When a class is passed as an argument returns true if all of the collection is a member of such class::Numeric I got a false here expecting a true.

2020-06-23 23:21 UTC, MarioDena commented on enumerable.rb
> +  end
Same problems from my_all? Maybe they are working the other-way around? Im getting false when expecting true.

2020-06-23 23:21 UTC, MarioDena commented on enumerable.rb
> +  end
- [ ] Same problem here, when no block or argument is given returns true only if none of the collection members is true.

2020-06-23 23:21 UTC, MarioDena commented on enumerable.rb
> +  end
- [ ] The error reported by @maelfosso persist my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.

2020-06-23 23:21 UTC, MarioDena commented on enumerable.rb
> +end
- [ ] my_inject should raise a "LocalJumpError" when no block or argument is given.

That's all please make the requested adjustments so all your classes behave exactly as the built in counterparts. 

Cheers!

2020-06-24 00:49 UTC, davitomix commented
## Hi. 👨‍🚀
### Very good job so far.

However, since the previous revision, there has been no change, there are still the same issues listed by the previous TSE.   ⚠️ 

****
**Please verify each of them and make the changes required and submit for re-review once you are ready!** 
****
### Status: Changes required. ♻️  
****


**[TSE:  David Elí]** 
Slack: @ David Eli Martinez Garcia

2020-06-24 10:02 UTC, mikenath223 requested changes
### Hi Team. 👋

**Nice job here, just a few more steps and we are good to go. 👌**

- [x] There are still issues with my_each and my_each_with_index:
- Both methods, when a range is passed, are expected to return a range but yours returns an array.
- Both methods, when a hash is passed to them, are expected to return a hash but yours returns a string containing the hash keys and values, kindly return a hash back under this condition.

- [x] my_all, when a class is passed, is expected to return true if the array passed to it contains elements that all belong to the class. Yours fails in this example `[1,2,3,4].my_all?(Numeric)`.  Kindly fix it.

- [x] my_any, when a class is passed, is expected to return true if at least one of the elements in the array passed to it belongs to the class. Yours fails in this example `[1,2,3,4].my_any?(Numeric)`.  Kindly fix this also.

- [ ] - my_map is expected to run only the proc when both a block and a proc are passed to it but it seems yours isn't structured to take a single argument as it throws an error of `wrong number of arguments given 1 expected 0`.

- [x] In addition, the live link that exists in your readMe currently leads nowhere, kindly remove it. Sorry, this wasn't mentioned in the previous reviews.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

🚀🚀HAPPY CODING🚀🚀

2020-06-24 12:56 UTC, lekegitrepo commented
### Good job :+1: 
#### This project is approved :100: :1st_place_medal:

#### _Reviewed by Temitayo Adeleke._

2020-06-24 12:56 UTC, lekegitrepo approved these changes
#### Status: Approved.

2020-06-24 13:15 UTC, merged