RSpec Testing for Enumerable Methods
Georjane/Enumerable-Methods pull request #4
Opened 2020-07-17 13:12 UTC by Georjane

We created different examples to test all Enumerable methods using RSpec (Test Driven Development)
- my_each
- my_each_with_index
- my_select
- my_all?
- my_any?
- my_none?
- my_count
- my_map
- my_inject

2020-07-17 13:42 UTC, Georjane commented
RSpec works just fine from the terminal but we don't know how to solve the RSpec setup error below

```
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /home/runner/work/Enumerable-Methods/Enumerable-Methods/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/bin/bundle:23:in `<main>'
```

2020-07-17 21:09 UTC, kobiyoyo reviewed
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [x] Let's reopen this PR.
- [x]  Let's edit this pull request to Gitflow.
- [x] Check comments below 


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-07-17 21:09 UTC, kobiyoyo commented on spec/enum_spec.rb
> +  end
Let test for when:
- [x] returns an Enumerator if no block is given
- [x] calls the given block once for each element in self

2020-07-17 21:09 UTC, kobiyoyo commented on spec/enum_spec.rb
> +  end
Let test for when:
- [x] returns an Enumerator if no block is given
- [x] calls the given block once for each element in self

2020-07-17 21:09 UTC, kobiyoyo commented on spec/enum_spec.rb
> +  end
Let test for when:
- [x] when a Regex is passed as an argument

2020-07-17 21:09 UTC, kobiyoyo commented on spec/enum_spec.rb
> +  end
Let test for when:
- [x] when a Regex is passed as an argument

2020-07-17 21:09 UTC, kobiyoyo commented on spec/enum_spec.rb
> +  end
Let test for when:
- [x] when a Regex is passed as an argument

2020-07-17 21:09 UTC, kobiyoyo commented on spec/enum_spec.rb
> +  end
Let test for when:
- [ ] returns an Enumerator if no block is given

2020-07-17 21:09 UTC, kobiyoyo commented on spec/enum_spec.rb
> +  end
Test for when :
- [ ] when a symbol is specified with an initail value

2020-07-20 09:01 UTC, mikenath223 requested changes
### Hi Team 👋

You've done quite well on this. 👍

However, let's fix this:

- [x] Kindly include in your readme instructions to run the tests. In addition, you have the steps in `Getting Started` in your readme mixed up, the user should first clone the project before `cd` into the project folder, not the other way round. Also, the folder to cd into is `Enumerable-Methods`, which is the actual name of your folder.

Kindly fix this issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-07-20 09:03 UTC, mikenath223 commented on spec/enum_spec.rb
> +  end
- [ ]  Also the wording of the context description here is wrong, it should read `When no block is given`. Please fix it.

2020-07-20 09:25 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

2020-07-20 09:34 UTC, merged